---
apiVersion: v1
kind: Namespace
metadata:
 name: testservice
---
apiVersion: v1
kind: Service
metadata:
 name: testservice
 namespace: testservice
spec:
 ports:
   - name: web
     port: 80
     targetPort: web
 selector:
   app: testservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: testservice
 namespace: testservice
spec:
 selector:
   matchLabels:
     app: testservice
 template:
   metadata:
     labels:
       app: testservice
   spec:
     containers:
       - name: testservice
         image: traefik/whoami
         ports:
           - name: web
             containerPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testservice.vps9.hochguertel.work-prod
  namespace: default
spec:
  secretName: testservice.vps9.hochguertel.work-prod
  commonName: "testservice.vps9.hochguertel.work"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "testservice.vps9.hochguertel.work"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: testservice
 namespace: testservice
 annotations:
   cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
 tls:
   - hosts:
       - testservice.vps9.hochguertel.work
     secretName: testservice.vps9.hochguertel.work-prod
 rules:
   - host: testservice.vps9.hochguertel.work
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: testservice
               port:
                 name: web
